# Generated by Django 5.2.7 on 2025-10-08 08:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IHG_Gateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHG_MQTTDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=100)),
                ("device_id", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IHG_InboundConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("connector_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "is_inbound",
                    models.BooleanField(
                        default=True, help_text="True=Inbound, False=Outbound"
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("interval", models.CharField(default="60", max_length=20)),
                ("maximum_data_points", models.CharField(default="100", max_length=20)),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("modbus", "Modbus"),
                            ("mqtt", "MQTT"),
                            ("snmp", "SNMP"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_connectors",
                        to="Gateway.ihg_gateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inbound Connector",
                "verbose_name_plural": "Inbound Connectors",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_name", models.CharField(max_length=100)),
                ("device_id", models.CharField(max_length=100)),
                (
                    "device_ip",
                    models.GenericIPAddressField(default="127.0.0.1", unpack_ipv4=True),
                ),
                ("device_port", models.PositiveIntegerField(default=0)),
                ("device_status", models.CharField(default="inactive", max_length=10)),
                (
                    "connector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="Gateway.ihg_inboundconnector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHG_MQTTConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("broker_ip", models.GenericIPAddressField(default="127.0.0.1")),
                ("port", models.PositiveIntegerField(default=1883)),
                (
                    "interval",
                    models.CharField(
                        blank=True, default="60s", max_length=20, null=True
                    ),
                ),
                ("username", models.CharField(blank=True, default="", max_length=100)),
                ("password", models.CharField(blank=True, default="", max_length=100)),
                (
                    "connector_inbound",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_config",
                        to="Gateway.ihg_inboundconnector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHG_MQTTData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=150)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mqtt_data",
                        to="Gateway.ihg_mqttdevice",
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"],},
        ),
        migrations.CreateModel(
            name="IHG_MQTTTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("String", "String"),
                            ("Integer", "Integer"),
                            ("Double", "Double"),
                            ("Boolean", "Boolean"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries",
                        to="Gateway.ihg_mqttdevice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHG_MQTTTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "mqtt_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="Gateway.ihg_mqttconfiguration",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ihg_mqttdevice",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="devices",
                to="Gateway.ihg_mqtttopic",
            ),
        ),
        migrations.CreateModel(
            name="IHG_OutboundConnector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("connector_id", models.UUIDField(default=uuid.uuid4)),
                (
                    "is_inbound",
                    models.BooleanField(
                        default=True, help_text="True=Inbound, False=Outbound"
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="inactive",
                        max_length=10,
                    ),
                ),
                ("interval", models.CharField(default="60", max_length=20)),
                ("maximum_data_points", models.CharField(default="100", max_length=20)),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("mqtt", "MQTT"),
                            ("rest", "REST"),
                            ("openadr-ven", "OpenADR-VEN"),
                            ("ocpp", "OCPP"),
                            ("file", "File"),
                            ("custom", "Custom"),
                        ],
                        max_length=30,
                    ),
                ),
                ("rest_url", models.URLField(blank=True, null=True)),
                (
                    "rest_method",
                    models.CharField(
                        choices=[("GET", "GET"), ("POST", "POST")],
                        default="POST",
                        max_length=10,
                    ),
                ),
                (
                    "certificate",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="Gateway/static/",
                        verbose_name="Certificate File",
                    ),
                ),
                (
                    "private_key",
                    models.FileField(
                        blank=True,
                        default=None,
                        null=True,
                        upload_to="Gateway/static/",
                        verbose_name="Private Key File",
                    ),
                ),
                (
                    "charge_point_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="OCPP Charge Point ID",
                    ),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="File Path"
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="outbound_connectors",
                        to="Gateway.ihg_gateway",
                    ),
                ),
            ],
            options={
                "verbose_name": "Outbound Connector",
                "verbose_name_plural": "Outbound Connectors",
            },
        ),
        migrations.AddField(
            model_name="ihg_mqttconfiguration",
            name="connector_outbound",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mqtt_config",
                to="Gateway.ihg_outboundconnector",
            ),
        ),
        migrations.CreateModel(
            name="IHG_SNMP_Timeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("datatype", models.CharField(default="", max_length=50)),
                ("address", models.CharField(default=0, max_length=100)),
                ("method", models.CharField(default="GET", max_length=10)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snmp_timeseries",
                        to="Gateway.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHG_Timeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("scale", models.FloatField()),
                ("address", models.CharField(max_length=100)),
                (
                    "byte_order",
                    models.CharField(
                        choices=[
                            ("AB", "AB"),
                            ("BA", "BA"),
                            ("ABCD", "ABCD"),
                            ("DCBA", "DCBA"),
                            ("CDAB", "CDAB"),
                            ("GHEFCDAB", "GHEFCDAB"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("UINT16", "UINT16"),
                            ("UINT32", "UINT32"),
                            ("UINT64", "UINT64"),
                            ("INT16", "INT16"),
                            ("INT32", "INT32"),
                            ("INT64", "INT64"),
                            ("FLOAT32-IEEE", "FLOAT32-IEEE"),
                            ("FLOAT64-IEEE", "FLOAT64-IEEE"),
                            ("FLOAT32", "FLOAT32"),
                            ("FIXED", "FIXED"),
                            ("UFIXED", "UFIXED"),
                            ("DOUBLE", "DOUBLE"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries",
                        to="Gateway.device",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IHG_ModbusData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("value", models.FloatField()),
                (
                    "timeseries",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modbus_data",
                        to="Gateway.ihg_timeseries",
                    ),
                ),
            ],
            options={"ordering": ["-timestamp"],},
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("sql", models.TextField()),
                ("options", models.JSONField(blank=True, null=True)),
                (
                    "actions",
                    models.JSONField(blank=True, default="inactive", null=True),
                ),
                (
                    "stream",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gateway.ihg_inboundconnector",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RuleChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.TextField(blank=True, null=True)),
                ("edges", models.TextField(blank=True, null=True)),
                (
                    "gateway",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Gateway.ihg_gateway",
                    ),
                ),
            ],
        ),
    ]
