# Generated by Django 3.2.25 on 2025-08-11 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IHG_Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='IHG_Timeseries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scale', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('byte_order', models.CharField(choices=[('AB', 'AB'), ('BA', 'BA'), ('ABCD', 'ABCD'), ('DCBA', 'DCBA'), ('CDAB', 'CDAB'), ('GHEFCDAB', 'GHEFCDAB')], max_length=20)),
                ('data_type', models.CharField(choices=[('UINT16', 'UINT16'), ('UINT32', 'UINT32'), ('UINT64', 'UINT64'), ('INT16', 'INT16'), ('INT32', 'INT32'), ('INT64', 'INT64'), ('FLOAT32-IEEE', 'FLOAT32-IEEE'), ('FLOAT64-IEEE', 'FLOAT64-IEEE'), ('FLOAT32', 'FLOAT32'), ('FIXED', 'FIXED'), ('UFIXED', 'UFIXED'), ('DOUBLE', 'DOUBLE')], max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeseries', to='Gateway.device')),
            ],
        ),
        migrations.CreateModel(
            name='IHG_OutboundConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('connector_type', models.CharField(choices=[('modbus', 'Modbus'), ('mqtt', 'MQTT'), ('http', 'HTTP'), ('custom', 'Custom')], max_length=30)),
                ('is_inbound', models.BooleanField(default=True, help_text='True=Inbound, False=Outbound')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_connectors', to='Gateway.ihg_gateway')),
            ],
            options={
                'verbose_name': 'Outbound Connector',
                'verbose_name_plural': 'Outbound Connectors',
            },
        ),
        migrations.CreateModel(
            name='IHG_MQTTConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_ip', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=1883)),
                ('interval', models.CharField(default='60s', max_length=20)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('topic', models.CharField(max_length=200)),
                ('connector', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='Gateway.ihg_outboundconnector')),
            ],
        ),
        migrations.CreateModel(
            name='IHG_InboundConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('connector_type', models.CharField(choices=[('modbus', 'Modbus'), ('mqtt', 'MQTT'), ('http', 'HTTP'), ('custom', 'Custom')], max_length=30)),
                ('is_inbound', models.BooleanField(default=True, help_text='True=Inbound, False=Outbound')),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=10)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_connectors', to='Gateway.ihg_gateway')),
            ],
            options={
                'verbose_name': 'Inbound Connector',
                'verbose_name_plural': 'Inbound Connectors',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='Gateway.ihg_inboundconnector'),
        ),
    ]
