# Generated by Django 3.2.25 on 2025-08-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', unpack_ipv4=True),
        ),
        migrations.AddField(
            model_name='device',
            name='device_port',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
