# Generated by Django 3.2.25 on 2025-08-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_mqttconfiguration',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
