# Generated by Django 3.2.25 on 2025-08-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0002_auto_20250812_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_status',
            field=models.CharField(default='inactive', max_length=10),
        ),
        migrations.CreateModel(
            name='IHG_ModbusData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField()),
                ('timeseries', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modbus_data', to='Gateway.ihg_timeseries')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
