# Generated by Django 3.2.25 on 2025-08-25 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0002_ihg_mqttconfiguration_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihg_mqttconfiguration',
            name='topic',
        ),
    ]
