# Generated by Django 3.2.25 on 2025-08-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0003_remove_ihg_mqttconfiguration_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihg_mqttconfiguration',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='ihg_mqttconfiguration',
            name='username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
