# Generated by Django 3.2.25 on 2025-08-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0003_auto_20250812_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_inboundconnector',
            name='interval',
            field=models.CharField(default='60', max_length=20),
        ),
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='interval',
            field=models.CharField(default='60', max_length=20),
        ),
    ]
