# Generated by Django 3.2.25 on 2025-08-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0004_auto_20250812_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_inboundconnector',
            name='Limit',
            field=models.CharField(default='100', max_length=20),
        ),
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='Limit',
            field=models.CharField(default='100', max_length=20),
        ),
    ]
