# Generated by Django 3.2.25 on 2025-09-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0004_auto_20250826_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('rest', 'REST'), ('openadr-ven', 'OpenADR-VEN'), ('custom', 'Custom')], max_length=30),
        ),
    ]
