# Generated by Django 3.2.25 on 2025-08-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0005_auto_20250812_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ihg_inboundconnector',
            old_name='Limit',
            new_name='maximum_data_points',
        ),
        migrations.RenameField(
            model_name='ihg_outboundconnector',
            old_name='Limit',
            new_name='maximum_data_points',
        ),
    ]
