# Generated by Django 3.2.25 on 2025-09-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0005_alter_ihg_outboundconnector_connector_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihg_outboundconnector',
            name='rest_method',
        ),
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='private_key',
            field=models.FileField(blank=True, default=None, null=True, upload_to='connector_keys/', verbose_name='Private Key File'),
        ),
    ]
