# Generated by Django 3.2.25 on 2025-09-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0006_auto_20250908_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to='connector_certs/', verbose_name='Certificate File'),
        ),
    ]
