# Generated by Django 3.2.25 on 2025-08-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0006_auto_20250812_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihg_inboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('modbus', 'Modbus'), ('mqtt', 'MQTT'), ('custom', 'Custom')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ihg_mqttconfiguration',
            name='broker_ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('custom', 'Custom')], max_length=30),
        ),
    ]
