# Generated by Django 3.2.25 on 2025-08-13 08:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0007_auto_20250812_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_inboundconnector',
            name='connector_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='connector_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
