# Generated by Django 3.2.25 on 2025-09-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0007_ihg_outboundconnector_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to='openadr/', verbose_name='Certificate File'),
        ),
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='private_key',
            field=models.FileField(blank=True, default=None, null=True, upload_to='openadr/', verbose_name='Private Key File'),
        ),
    ]
