# Generated by Django 3.2.25 on 2025-08-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0008_auto_20250813_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihg_mqttconfiguration',
            name='interval',
            field=models.CharField(blank=True, default='60s', max_length=20, null=True),
        ),
    ]
