# Generated by Django 3.2.25 on 2025-08-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0009_alter_ihg_mqttconfiguration_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='rest_method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST')], default='POST', max_length=10),
        ),
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='rest_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('restapi', 'REST API'), ('custom', 'Custom')], max_length=30),
        ),
    ]
