# Generated by Django 3.2.25 on 2025-08-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0010_auto_20250819_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('rest', 'REST'), ('custom', 'Custom')], max_length=30),
        ),
    ]
