# Generated by Django 3.2.25 on 2025-09-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0011_auto_20250908_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihg_outboundconnector',
            name='charge_point_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='OCPP Charge Point ID'),
        ),
        migrations.AlterField(
            model_name='ihg_outboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('mqtt', 'MQTT'), ('rest', 'REST'), ('openadr-ven', 'OpenADR-VEN'), ('ocpp', 'OCPP'), ('custom', 'Custom')], max_length=30),
        ),
    ]
