# Generated by Django 3.2.25 on 2025-08-20 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0011_alter_ihg_outboundconnector_connector_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ihg_mqttconfiguration',
            name='connector',
        ),
        migrations.AddField(
            model_name='ihg_mqttconfiguration',
            name='connector_inbound',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='Gateway.ihg_inboundconnector'),
        ),
        migrations.AddField(
            model_name='ihg_mqttconfiguration',
            name='connector_outbound',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_config', to='Gateway.ihg_outboundconnector'),
        ),
        migrations.AlterField(
            model_name='ihg_inboundconnector',
            name='connector_type',
            field=models.CharField(choices=[('modbus', 'Modbus'), ('mqtt', 'MQTT'), ('rest', 'REST'), ('custom', 'Custom')], max_length=30),
        ),
    ]
