# Generated by Django 3.2.25 on 2025-08-20 08:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gateway', '0012_auto_20250820_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='IHG_MQTTData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=150)),
                ('key', models.CharField(max_length=150)),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mqtt_data', to='Gateway.ihg_mqttconfiguration')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
